### ISSUE TITLE
Cant use PUT POST in ContentSection

### ISSUE THREAD

**Issue by wolffsen** [fredsakr/eloqua-csharp-rest-client#7]
The Assets/ContentSection have a default url of /assets/contentSections in the Client. For operations like PUT and POST it should be /assets/contentSection

**Comment by fredsakr** [comment]
Thank you for catching this! :) We've updated the master branch to include a fix for this issue. We're now using the singular (/assets/contentSection) for operations like PUT and POST.

Thanks again for the feedback :)
