### ISSUE TITLE
Access to 'internalName' property on fields

### ISSUE THREAD

**Issue by lornemcintosh** [fredsakr/eloqua-csharp-rest-client#8]
It would be useful to have access to the 'internalName' property on fields, for instance in ContactField. (It seems like it was possible at one point, but it's been commented-out along with several others: https://github.com/fredsakr/eloqua-csharp-rest-client/blob/master/EloquaClient/Models/Assets/DataField.cs#L11)

**Comment by fredsakr** [comment]
A fix for this issue has been applied in the most recent commit.
